access_token: 8026383c-1c63-11ec-821e-7eab90446076
client_id: main
client_secret: ac178876-b829-11e9-b8c8-ac1f6b94fd9c
custom_variables:
  basket_double: 618523
  basket_productid: 618523
  compare_sections: 598682
  confirm_code: 111111
  coupon: SL-4JPWV-18GVF9B
  favorite_id: 623277
  favorite_id_double: 604945
  number: 79996666666
  order_coupon: vigodno10
  password: 111111
  product_id: 24617
  subscribe_device: 1a418dbe-b9f3-11ea-a96b-b42e9981f624
  user_email: test1101111@yandex.ru
  user_name: Test
delete_user: b0e90087-f447-11eb-9c0e-f2dfe89e1ff8
headers:
  Authorization: Bearer 8026383c-1c63-11ec-821e-7eab90446076
host: https://stage.05.ru/api/v2
refresh_token: 8026d1ca-1c63-11ec-821e-7eab90446076
variables:
  TestAboutRecomendDeveloper: {}
  TestAddQuestion: {}
  TestAddReview: {}
  TestAuthUser: {}
  TestBonusCodeSend: {}
  TestBonusFields: {}
  TestBonusInfo: {}
  TestBonusPhysical: {}
  TestBrand: {}
  TestBrandGroupped: {}
  TestBrandPopulars: {}
  TestCatalog: {}
  TestCatalogBanners: {}
  TestCatalogCategories: {}
  TestCatalogPanel: {}
  TestCatalogPaths: {}
  TestCatalogProductsViewed: {}
  TestCatalogSections: {}
  TestChangePersonalDataUser: {}
  TestCompare: {}
  TestCompareAllProducts: {}
  TestCompareSections: {}
  TestCompareStruct: {}
  TestComplaint: {}
  TestConfirmCode: {}
  TestDelBasketAll: {}
  TestDelBasketProductId: {}
  TestDelCompare: {}
  TestDelCompareProducts: {}
  TestDelCompareSection: {}
  TestDelOrderCoupon: {}
  TestDelPush: {}
  TestDeleteUser: {}
  TestEventsViewed: {}
  TestFavorite: {}
  TestFavoriteList: {}
  TestFavoriteProduct: {}
  TestFavoriteProductAllDel: {}
  TestFavoriteProductDel: {}
  TestFavoriteProductDouble: {}
  TestFeedbackParagraphs: {}
  TestFeedbacks: {}
  TestFeedbacksRequest: {}
  TestFoundCheaper: {}
  TestGetBasket: {}
  TestGetReleases: {}
  TestHomeScreen: {}
  TestInstallment: {}
  TestLocations: {}
  TestLocationsCurrent: {}
  TestOauthToken: {}
  TestOrderBasket: {}
  TestOrderBasketDouble: {}
  TestOrderCancel: {}
  TestOrderCoupon: {}
  TestOrderCreate:
    ORDER_ID: 149052
  TestOrderDelivery: {}
  TestOrderGifts: {}
  TestOrderOneclick: {}
  TestOrderPayment: {}
  TestPcbuild: {}
  TestPcbuildComponents: {}
  TestPcbuildScheme: {}
  TestPersonalArea: {}
  TestProductCard: {}
  TestProductViewed: {}
  TestProvider: {}
  TestPushEvents: {}
  TestQuantityBasket: {}
  TestQuestionAnswer: {}
  TestQuestionAnswerDislike: {}
  TestQuestionAnswerFields: {}
  TestQuestionAnswerLike: {}
  TestQuestionDislikeQuestionId: {}
  TestQuestionFields: {}
  TestQuestionLikeQuestionId: {}
  TestQuestionProductId: {}
  TestQuestionQuestionId: {}
  TestQuetion: {}
  TestRecOrderCreation: {}
  TestRecommendDeveloper: {}
  TestRecoverChange: {}
  TestRecoverSend: {}
  TestRegBonus: {}
  TestRegisterCode: {}
  TestRegisterFields: {}
  TestRegisterUser: {}
  TestReleasesList: {}
  TestReviewComment: {}
  TestReviewCommentDislike: {}
  TestReviewCommentFields: {}
  TestReviewCommentLike: {}
  TestReviewDislike: {}
  TestReviewFields: {}
  TestReviewLike: {}
  TestReviewProduct: {}
  TestReviewProductId: {}
  TestReviewidComments: {}
  TestSearch: {}
  TestSearchHints: {}
  TestSearchPhrases: {}
  TestSetLocation: {}
  TestSliders: {}
  TestSubscribeDevice: {}
  TestSupportInformation: {}
  TestSupportStores: {}
  TestUnsubscribe: {}
  TestUserExist: {}
  TestUserOrders: {}
  TestUserVerifyEmail: {}
  TestVacancy: {}
  TestVacancyId: {}
  TestVueCatalog: {}
  TestWholesaler: {}
