access_token: 8185faa3-ceb4-11eb-a645-0242ac150004
client_id: main
client_secret: ac178876-b829-11e9-b8c8-ac1f6b94fd9c
headers:
  Authorization: Bearer 8185faa3-ceb4-11eb-a645-0242ac150004
host: https://05.ru/api/v2
refresh_token: ac1987a6-da7f-11eb-b7ed-8a36c8533520
variables:
  TestAboutRecomendDeveloper: {}
  TestAuthUser: {}
  TestBonusCodeSend: {}
  TestBonusFields: {}
  TestBonusInfo: {}
  TestBrand: {}
  TestBrandGroupped: {}
  TestBrandPopulars: {}
  TestCatalog: {}
  TestCatalogBanners: {}
  TestCatalogCategories: {}
  TestCatalogPanel: {}
  TestCatalogPaths: {}
  TestCatalogProductsViewed: {}
  TestChangePersonalDataUser: {}
  TestCompare: {}
  TestCompareAllProducts: {}
  TestCompareSections: {}
  TestCompareStruct: {}
  TestComplaint: {}
  TestConfirmCode: {}
  TestDelBasketAll: {}
  TestDelBasketProductId: {}
  TestDelCompare: {}
  TestDelCompareProducts: {}
  TestDelCompareSection: {}
  TestDelOrderCoupon: {}
  TestDelPush: {}
  TestDeleteUser: {}
  TestEventsViewed: {}
  TestFavorite: {}
  TestFavoriteList: {}
  TestFavoriteProduct: {}
  TestFavoriteProductAllDel: {}
  TestFavoriteProductDel: {}
  TestFavoriteProductDouble: {}
  TestFeedbackParagraphs: {}
  TestFeedbacks: {}
  TestFeedbacksRequest: {}
  TestFoundCheaper: {}
  TestGetBasket: {}
  TestHomeScreen: {}
  TestInstallment: {}
  TestLocations: {}
  TestLocationsCurrent: {}
  TestOauthToken: {}
  TestOrderBasket: {}
  TestOrderBasketDouble: {}
  TestOrderCancel: {}
  TestOrderCoupon: {}
  TestOrderCreate:
    ORDER_ID: 78620
  TestOrderDelivery: {}
  TestOrderGifts: {}
  TestOrderOneclick: {}
  TestOrderPayment: {}
  TestPersonalArea: {}
  TestProductCard: {}
  TestProductViewed: {}
  TestPushEvents: {}
  TestQuantityBasket: {}
  TestQuestionAnswer: {}
  TestQuestionAnswerDislike: {}
  TestQuestionAnswerFields: {}
  TestQuestionAnswerLike: {}
  TestQuestionDislikeQuestionId: {}
  TestQuestionFields: {}
  TestQuestionLikeQuestionId: {}
  TestQuestionProductId: {}
  TestQuestionQuestionId: {}
  TestRecOrderCreation: {}
  TestRecommendDeveloper: {}
  TestRecoverChange: {}
  TestRecoverSend: {}
  TestRegBonus: {}
  TestRegisterCode: {}
  TestRegisterFields: {}
  TestRegisterUser: {}
  TestReviewComment: {}
  TestReviewCommentDislike: {}
  TestReviewCommentFields: {}
  TestReviewCommentLike: {}
  TestReviewDislike: {}
  TestReviewFields: {}
  TestReviewLike: {}
  TestReviewProductId: {}
  TestReviewidComments: {}
  TestSearch: {}
  TestSearchHints: {}
  TestSearchPhrases: {}
  TestSetLocation: {}
  TestSliders: {}
  TestSubscribeDevice: {}
  TestSupportInformation: {}
  TestSupportStores: {}
  TestUnsubscribe: {}
  TestUserExist: {}
  TestUserOrders: {}
  TestUserVerifyEmail: {}
  TestVacancy: {}
  TestVacancyId: {}
  TestVueCatalog: {}
